# -*- coding: utf-8 -*-
"""chat_bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nmDhBZ2ZwUP8fBrqVo12fkOf-Z1pzISa
"""

pip install nltk

import nltk
from nltk.chat.util import Chat, reflections

pairs = [
    [
        r"my name is (.*)",
        ["Hello %1, how are you today?",]
    ],
    [
        r"hi|hey|hello",
        ["Hello!", "Hey there!",]
    ],
    [
        r"what is your name?",
        ["I am a chatbot created by OpenAI. You can call me ChatGPT.",]
    ],
    [
        r"how are you?",
        ["I'm just a bunch of code, so I don't have feelings, but I'm here to help you!",]
    ],
    [
        r"sorry (.*)",
        ["It's okay, no problem.",]
    ],
    [
        r"I am fine",
        ["Great to hear that! How can I assist you today?",]
    ],
    [
        r"quit",
        ["Goodbye! It was nice talking to you. Have a great day!",]
    ],
    [
        r"(.*)",
        ["I'm sorry, I don't understand that. Could you please rephrase?",]
    ],
]

def chatbot():
    print("Hi! I am a simple chatbot. You can talk to me by typing in the console. Type 'quit' to exit.")
    chat = Chat(pairs, reflections)
    chat.converse()

if __name__ == "__main__":
    chatbot()

# prompt: pip install nltk
# pip install pyttsx3
# pip install chatterbot
# pip install chatterbot_corpus

!pip install nltk
!pip install pyttsx3
!pip install chatterbot
!pip install chatterbot_corpus

import nltk
from nltk.chat.util import Chat, reflections
import pyttsx3
from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer

